name: Protobuf
on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - "feat/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v2
      - name: gen proto
        run: make gen-proto
      - name: update proto dependency
        run: make proto-update-deps
      - name: lint
        run: make proto-lint